[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
python = ">3.10"
numpy = ">=2.4.2,<3"
xrayphysics = { path = "." }

[package]
name = "xrayphysics"
version = "1.2.1"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
